#!/bin/sh
# Northstar one-command installer.
#   curl -fsSL https://raw.githubusercontent.com/ErzenXz/northstar/main/deploy/install.sh | sh
# Creates ./northstar with a production compose file, generates secrets, and starts the forge.
set -eu

COMPOSE_URL="https://raw.githubusercontent.com/ErzenXz/northstar/main/deploy/compose.yaml"
DIR="${NORTHSTAR_DIR:-northstar}"

say() { printf "\033[1;35m[northstar]\033[0m %s\n" "$1"; }
fail() { printf "\033[1;31m[northstar]\033[0m %s\n" "$1" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || fail "Docker is required. Install it from https://docs.docker.com/get-docker/ and rerun."
docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required (the 'docker compose' command)."
docker info >/dev/null 2>&1 || fail "The Docker daemon is not running. Start Docker and rerun."

random_secret() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32; else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

say "Setting up in ./${DIR}"
mkdir -p "$DIR"
cd "$DIR"

if [ -f .env ]; then
  say "Existing .env found — keeping your secrets."
else
  say "Generating secrets"
  cat > .env <<ENV
# Generated by the Northstar installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_PASSWORD=$(random_secret)
NORTHSTAR_ENCRYPTION_KEY=$(random_secret)
SESSION_SECRET=$(random_secret)

# Public URLs — change these when you put Northstar behind a domain/TLS proxy.
NORTHSTAR_BASE_URL=http://localhost:3000
NORTHSTAR_GIT_URL=http://localhost:4000
NORTHSTAR_SSH_URL=ssh://git@localhost:2222

# Optional: enable AI analysis and semantic review.
AI_GATEWAY_API_KEY=
# Optional: enable transactional email.
RESEND_API_KEY=
ENV
  chmod 600 .env
fi

say "Fetching compose file"
curl -fsSL "$COMPOSE_URL" -o compose.yaml

say "Pulling images and starting Northstar"
docker compose pull --quiet
docker compose up -d

say ""
say "Northstar is starting at http://localhost:3000"
say "Git over HTTP:  http://localhost:4000    Git over SSH: port 2222"
say "Create the first account in your browser — it becomes your workspace."
say "Manage with: cd ${DIR} && docker compose [logs|ps|down|pull]"
