import Link from "next/link";
import { notFound } from "next/navigation";
import { CircleDot, Flag, MessageSquare, Plus, Tag } from "lucide-react";
import { eq } from "drizzle-orm";
import { getDb, labels, milestones } from "@origin/db";
import { createIssueAction, createLabelAction, createMilestoneAction } from "@/app/actions";
import { EmptyState } from "@/components/empty-state";
import { RepoShell } from "@/components/repo-shell";
import { getRepository, getRepositoryIssues } from "@/lib/data";

export const metadata = { title: "Issues" };

export default async function IssuesPage({ params }: { params: Promise<{ owner: string; repo: string }> }) {
  const { owner, repo } = await params;
  const row = await getRepository(owner, repo);
  if (!row) notFound();
  const [items, repoLabels, repoMilestones] = await Promise.all([getRepositoryIssues(row.repository.id), getDb().select().from(labels).where(eq(labels.repositoryId, row.repository.id)), getDb().select().from(milestones).where(eq(milestones.repositoryId, row.repository.id))]);
  return <RepoShell organization={row.organization} repository={row.repository} active="issues"><div className="section-heading"><div><p className="eyebrow-simple">WORK TO BE DONE</p><h1>Issues</h1><p>Problems, ideas, and outcomes with their full working conversation.</p></div><div className="action-cluster"><details className="popover-form"><summary className="button"><Tag size={16}/> Labels</summary><form action={createLabelAction} className="panel"><input type="hidden" name="repositoryId" value={row.repository.id}/><label>Name<input name="name" required/></label><label>Color<input name="color" defaultValue="4f76ff" pattern="[0-9a-fA-F]{6}"/></label><label>Description<input name="description"/></label><button className="button button-primary">Create label</button><small>{repoLabels.length} native labels</small></form></details><details className="popover-form"><summary className="button"><Flag size={16}/> Milestones</summary><form action={createMilestoneAction} className="panel"><input type="hidden" name="repositoryId" value={row.repository.id}/><label>Title<input name="title" required/></label><label>Outcome<textarea name="description" rows={3}/></label><button className="button button-primary">Create milestone</button><small>{repoMilestones.length} milestones</small></form></details><details className="popover-form"><summary className="button button-primary"><Plus size={16} /> New issue</summary><form action={createIssueAction} className="panel"><input type="hidden" name="repositoryId" value={row.repository.id} /><label>What needs to change?<input name="title" required minLength={3} placeholder="Clear outcome, not a vague task" /></label><label>Context and acceptance<textarea name="body" rows={6} placeholder="What is happening, what should happen, and how will we know it works?" /></label><button className="button button-primary">Create issue</button></form></details></div></div><div className="filter-bar"><button className="active"><CircleDot size={15} /> Open</button><button>Closed</button><span>{items.filter((item) => item.status === "open").length} open · {items.filter((item) => item.status !== "open").length} closed</span></div>{items.length ? <section className="work-list panel">{items.map((issue) => <Link href={`/${owner}/${repo}/issues/${issue.number}`} key={issue.id}><CircleDot className={issue.status === "open" ? "status-open" : "status-closed"} /><div><h2>{issue.title}</h2><p>#{issue.number} opened by {issue.authorName} · updated {issue.updatedAt.toLocaleDateString()}</p><div>{issue.labels.map((label) => <span className="label" key={label}>{label}</span>)}</div></div><span className="comment-count"><MessageSquare size={15} /></span></Link>)}</section> : <EmptyState icon={<CircleDot />} title="No issues yet" detail="Turn a product problem or idea into a clear outcome for a person or agent." />}</RepoShell>;
}
